name = "navpilot"
main = "src/index.js"
compatibility_date = "2024-05-12"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "vector-index"

[[d1_databases]]
binding = "DB"
database_name = "database"
database_id = "4c6131f6-3a69-4912-80f3-b6bc7250c0ac"